package com.example.democashfree.Api;

public class Transaction {
    public int id;
    public int userId;
    public int standardId;
    public String date;
    public String dueDate;
    public String paymentDate;
    public String refundDate;
    public String transferDate;
    public String paymentId;
    public String amount;
    public double transactionFee;
    public double settlementFee;
    public float amountPayable;
    public double processignPaidByIns;
    public String org;
    public String orgId;
    public String orgName;
    public String payment_method;
    public String attempt;
    public String status;
    public String trnsDetails;
    public String receipt;
    public String callback;
    public String note;
    public String linkSentBy;
    public String refundedBy;
    public String transferedBy;
    public String transactionPaidBy;
    public String gst;
    public boolean gstApplicable;
    public String discount_details;
    public String addition_details;
    public int total_discount;
    public int total_addition;
    public String payment_type;
    public String cheque_no;
    public User user;
}
